# Generated by Django 5.0.6 on 2024-05-08 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('fecha_carga', models.DateField(auto_now=True)),
            ],
        ),
    ]
