# Generated by Django 5.0.6 on 2024-05-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_remove_consumidor_is_staff_consumidor_usuario_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumidor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='consumidor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='user_permissions',
        ),
    ]
