# Generated by Django 5.0.6 on 2024-05-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_consumidor_options_alter_consumidor_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumidor',
            managers=[
            ],
        ),
    ]
