# Generated by Django 5.0.6 on 2024-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_alter_consumidor_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Usuarios/perfiles/', verbose_name='Imagen de Perfil'),
        ),
    ]
