# Generated by Django 5.0.6 on 2024-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_alter_consumidor_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumidor',
            options={},
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
