# Generated by Django 5.0.6 on 2024-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_alter_consumidor_options_consumidor_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidor',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Username'),
        ),
    ]
