name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
        pip uninstall -r requirements.txt -y
        pip install -r requirements.txt


    - name: Crear la carpeta para sortear incongruencias
      run: mkdir -p Apps/Usuarios

    - name: Generate Firebase Admin SDK JSON file
      env:
          ADMIN_FIREBASE: ${{ secrets.ADMIN_FIREBASE }}
      run: |
        echo "$ADMIN_FIREBASE" > Apps/Usuarios/ecoweb-fc73c-firebase-adminsdk-20hmv-feea5a9108.json

    - name: Copiar Firebase Admin SDK JSON file
      run: cp Apps/Usuarios/ecoweb-fc73c-firebase-adminsdk-20hmv-feea5a9108.json EcoWEB/Apps/Usuarios/ecoweb-fc73c-firebase-adminsdk-20hmv-feea5a9108.json

    - name: Run Tests
      run: |
        python EcoWEB/manage.py test
